### ISSUE TITLE
Initial weights are not preserved

### ISSUE THREAD

**Issue by samczsun** [balancer-labs/configurable-rights-pool#14]
https://github.com/balancer-labs/configurable-rights-pool/blob/be02d74740add29aed928e8dc598356f0181f961/contracts/ConfigurableRightsPool.sol#L566-L568

The `_startWeights` array initially stores the weights specified by the pool creator. However, when `updateWeightsGradually` is called it gets replace with the new starting weights.

https://github.com/balancer-labs/configurable-rights-pool/blob/be02d74740add29aed928e8dc598356f0181f961/contracts/ConfigurableRightsPool.sol#L381-L395

Then, if the pool is re-created, the modified start weights will be used instead of the original weights.

**Comment by EndymionJkb** [comment]
Well, right now you can't recreate a pool (i.e., call createPool() more than once), so maybe this is ok. We definitely intend for updateWeightsGradually to be called multiple times. That can be done to "adjust" the curve mid-stream, or "freeze" the current weights, etc. So startWeights does just mean the starting weights the last time it was called.

I'd explored the idea of recreating pools in an "auction" context, where you might want to be able to re-use the contract for a different auction (with the same token and parameters, of course). Consider a two-token pool with a project token you're "selling," and a collateral token like Dai. You updateWeightsGradually (like a liquidity bootstrapping pool), and at the end, recover the proceeds with "removeToken". Removing all the tokens "kills" the pool. You cannot add any tokens back in; it reverts with division by zero trying to compute the number of pool tokens. As written, it's dead and you just have to deploy a new contract.

However, if you reset the bPool pointer to 0, it *would* let you call createPool() again. And you're right; it would have this problem. I commented how it would need to *not* destroy the _tokens (_initialTokens) in this case. But it also would have to store the original weights.

Furthermore, you would be able to change the time block parameters on a new call to createPool as well, which I'm not sure is a problem, but might not be expected behavior.

I think the solution (at least for now) is to remove the comments suggesting how, with certain code changes, you might re-create the pool. It's too much work for an edge case, and Fernando said he's fine with "killing" the pool - it's the same behavior as the core pools.

**Comment by EndymionJkb** [comment]
And while we're on the subject of clear names, might as well go all the way. How about this?

    struct PoolParams {
        // Balancer Pool Token (representing shares of the pool)
        string poolTokenSymbol;
        string poolTokenName;
        // Tokens inside the Pool
        address[] constituentTokens;
        uint[] tokenBalances;
        uint[] tokenWeights;
        uint swapFee;
    }

**Comment by samczsun** [comment]
Resolved in https://github.com/balancer-labs/configurable-rights-pool/commit/5450f5e57f8d1d3b2f8125670a5f7d40c85f54a9
