### ISSUE TITLE
Incorrect check when decreasing weight of token

### ISSUE THREAD

**Issue by samczsun** [balancer-labs/configurable-rights-pool#16]
https://github.com/balancer-labs/configurable-rights-pool/blob/be02d74740add29aed928e8dc598356f0181f961/libraries/SmartPoolManager.sol#L68-L75

Imagine a max total weight of 100, and 3 tokens:
- Token A, weight 30
- Token B, weight 40,
- Token C, weight 30

Now we want to reduce the weight of Token B to 30. The new weight is less than the current weight, so the delta weight is 10. The current total weight is already 100, causing the check that `100 + 10 <= 100` to incorrectly fail

**Comment by EndymionJkb** [comment]
I think we just don't need this check, then. (I looked at the original code; this has been in there since the beginning.) Decreasing a weight can't cause the total to go over.

However, it made me think of another defensive programming measure - updateWeight could result in minting pool tokens, as would applyAddToken, so I should add "withinCap" modifiers to those functions. Mainly as documentation; I have a "catch-all" withinCap on the mint functions themselves just in case it's missed somewhere else, so it would revert anyway.

**Comment by samczsun** [comment]
Resolved in https://github.com/balancer-labs/configurable-rights-pool/commit/44b09fcba531f819cb8d5bf35ed7be221435748b
